version: "3.9"
services:
  users_db:
    container_name: users-db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: users_db
    volumes:
      - data-users:/var/lib/mysql
    restart: always
    networks:
      - spring

  courses_db:
    container_name: courses_db
    image: mysql:latest
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: courses_db
    volumes:
      - data-courses:/var/lib/mysql
    restart: always
    networks:
      - spring

  user-service:
    container_name: user-service
    image: palavecinofranco/user-service
#    build:
#      context: ./
#      dockerfile: ./user-service/Dockerfile
    ports:
      - "8001:8001"
    networks:
      - spring
    depends_on:
      - users_db
    restart: always

  course-service:
    container_name: course-service
    image: palavecinofranco/course-service
#    build:
#      context: ./
#      dockerfile: ./course-service/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - spring
    depends_on:
      - courses_db
    restart: always

volumes:
  data-courses:
    name: data-courses
  data-users:
    name: data-users

networks:
  spring: